services:
  runner-image:
    image: dh-mirror.gitverse.ru/library/python:3.12-slim
    command: ["true"]
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - PORT=4000
      - CLIENT_ORIGIN=https://code-room.bob-srv.ru
      - RUNNER_IMAGE=dh-mirror.gitverse.ru/library/python:3.12-slim
      - RUN_TIMEOUT_MS=15000
      - RUN_OUTPUT_LIMIT_BYTES=65536
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      runner-image:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - VITE_API_URL=https://code-room.bob-srv.ru
        - VITE_WS_URL=wss://code-room.bob-srv.ru
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
