services:
  backend:
    image: ghcr.io/bobrovtd/coderoom-backend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - PORT=4000
      - CLIENT_ORIGIN=https://code-room.bob-srv.ru
      - RUNNER_IMAGE=ghcr.io/bobrovtd/coderoom-runner:latest
      - RUN_TIMEOUT_MS=15000
      - RUN_OUTPUT_LIMIT_BYTES=65536
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  frontend:
    image: ghcr.io/bobrovtd/coderoom-frontend:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
