FROM dh-mirror.gitverse.ru/library/node:24-slim AS build

WORKDIR /app
COPY package*.json .npmrc ./
RUN npm ci
COPY . .
RUN npm run build

FROM dh-mirror.gitverse.ru/library/node:24-slim AS production

WORKDIR /app
ENV NODE_ENV=production
COPY package*.json .npmrc ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist

EXPOSE 4000
CMD ["npm", "start"]
