server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Возвращаем 404 для healthcheck, чтобы скрипт на странице понимал,
    # что реальный бэкенд еще не запущен.
    location = /health {
        return 404;
    }

    # Все остальные запросы (например, /rooms/xyz) перенаправляем на index.html,
    # чтобы у пользователя отображалась красивая страница-заглушка вместо Nginx 404.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
